[package]
name = "applit"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
log = "0.4.22"
regex = "1.10.6"
sha3 = "0.10.8"
serde = { version = "1.0", features = ["derive"] }
threadpool = "1.8.1"
crossbeam-channel = "0.5.13"